app-admin/logrotate
<#if architecture == "x86_64">
app-admin/mcelog
</#if>
app-admin/sudo
app-admin/syslog-ng
app-admin/sysstat
app-editors/vim
app-misc/screen
app-misc/tmux
app-portage/eix
app-portage/gentoolkit
dev-lang/php
net-analyzer/fail2ban
net-analyzer/nrpe
net-dns/djbdns
net-misc/dhcpcd
net-misc/ntp
sys-apps/mlocate
sys-cluster/ganglia
sys-fs/mdadm
sys-kernel/gentoo-sources
sys-process/atop
sys-process/htop
sys-process/lsof
sys-process/vixie-cron
