app-admin/logrotate
<#if architecture == "x86_64">
app-admin/mcelog
</#if>
app-admin/sudo
app-admin/sysstat
app-editors/nano
app-editors/vim
app-misc/screen
app-misc/tmux
app-portage/eix
app-portage/gentoolkit
app-portage/mirrorselect
dev-lang/php
dev-python/setuptools
net-analyzer/fail2ban
net-analyzer/nrpe
net-dns/djbdns
net-misc/dhcpcd
net-misc/ntp
sys-apps/mlocate
sys-cluster/ganglia
sys-process/atop
sys-process/htop
sys-process/lsof
