USE mysql;

DELETE
FROM user
WHERE User LIKE 'root';

DELETE
FROM db;

GRANT
ALL
ON *.*
TO 'bmoorman'@'%' IDENTIFIED BY PASSWORD '%BMOORMAN_HASH%'
WITH GRANT OPTION;

GRANT
ALL
ON *.*
TO 'cplummer'@'%' IDENTIFIED BY PASSWORD '%CPLUMMER_HASH%'
WITH GRANT OPTION;

GRANT
REPLICATION SLAVE
ON *.*
TO 'replication'@'10.%' IDENTIFIED BY '%REPLICATION_AUTH%';

GRANT
PROCESS, SUPER, REPLICATION CLIENT
ON *.*
TO 'monitoring'@'localhost' IDENTIFIED BY '%MONITORING_AUTH%';

GRANT
PROCESS
ON *.*
TO 'mytop'@'localhost' IDENTIFIED BY '%MYTOP_AUTH%';

RESET MASTER;

FLUSH PRIVILEGES;

CHANGE MASTER TO
master_host = '%MASTER_HOST%',
master_user = 'replication',
master_password = '%MASTER_AUTH%';

START SLAVE;
